/****************islam gamal***************/
#ifndef Timers_Reg_H_
#define Timers_Reg_H_

#include "std_Types.h"

#define GPT_Timer0_BASE 			(0x40030000)
#define GPT_Timer1_BASE 			(0x40031000)
#define GPT_Timer2_BASE 			(0x40032000)
#define GPT_Timer3_BASE 			(0x40033000)
#define GPT_Timer4_BASE 			(0x40034000)
#define GPT_Timer5_BASE 			(0x40035000)
#define GPT_WIDE_Timer0_BASE 	(0x40036000)
#define GPT_WIDE_Timer1_BASE 	(0x40037000)
#define GPT_WIDE_Timer2_BASE 	(0x4004C000)
#define GPT_WIDE_Timer3_BASE 	(0x4004D000)
#define GPT_WIDE_Timer4_BASE 	(0x4004E000)
#define GPT_WIDE_Timer5_BASE 	(0x4004F000)
#define RCGC_TIMER_BASE				(0x400FE000)


#define GPT_MIMR_OFFSET		  (0x018)         
#define GPT_MCFG_OFFSET		  (0x000)          
#define GPT_MTAV_OFFSET		  (0x050)          
#define GPT_MCTL_OFFSET		  (0x00C)        
#define GPT_MTAMR_OFFSET		(0x004)        
#define GPT_MTBMR_OFFSET		(0x008)         
#define GPT_MTAPS_OFFSET		(0x05C)          
#define GPT_MTBPS_OFFSET		(0x060)         
#define GPT_MTAPV_OFFSET		(0x064)         
#define GPT_MTBPV_OFFSET		(0x068)       
#define GPT_MPP_OFFSET		``(0xFC0)         
#define RCGC_TIMER_OFFSET		(0x604)						
#define RCGCW_TIMER_OFFSET	(0x65C)					
#define GPT_MTAPR_OFFSET		(0x038)					
#define GPT_MTBPR_OFFSET		(0x03C)					
#define GPT_MTAILR_OFFSET	  (0x028)					
#define GPT_MTBILR_OFFSET	  (0x02C)					
#define GPT_MICR_OFFSET		  (0x024)					


#define RCGC_TIMER_Reg 				(*(u32 volatile*)(RCGC_TIMER_OFFSET+RCGC_TIMER_BASE))
#define RCGCW_TIMER_Reg 			(*(u32 volatile*)(RCGC_TIMER_OFFSET+RCGC_TIMER_BASE))


#define GPT_MIMR_Timer0_REG     (*(u32 volatile*)(GPT_Timer0_BASE+GPT_MIMR_OFFSET))
#define GPT_MCFG_Timer0_REG     (*(u32 volatile*)(GPT_Timer0_BASE+GPT_MCFG_OFFSET))
#define GPT_MTAV_Timer0_REG     (*(u32 volatile*)(GPT_Timer0_BASE+GPT_MTAV_OFFSET))
#define GPT_MCTL_Timer0_REG     (*(u32 volatile*)(GPT_Timer0_BASE+GPT_MCTL_OFFSET))
#define GPT_MTAMR_Timer0_REG    (*(u32 volatile*)(GPT_Timer0_BASE+GPT_MTAMR_OFFSET))
#define GPT_MTBMR_Timer0_REG    (*(u32 volatile*)(GPT_Timer0_BASE+GPT_MTBMR_OFFSET))
#define GPT_MTAPS_Timer0_REG    (*(u32 volatile*)(GPT_Timer0_BASE+GPT_MTAPS_OFFSET))
#define GPT_MTBPS_Timer0_REG    (*(u32 volatile*)(GPT_Timer0_BASE+GPT_MTBPS_OFFSET))
#define GPT_MTAPV_Timer0_REG    (*(u32 volatile*)(GPT_Timer0_BASE+GPT_MTAPV_OFFSET))
#define GPT_MTBPV_Timer0_REG    (*(u32 volatile*)(GPT_Timer0_BASE+GPT_MTBPV_OFFSET))
#define GPT_MPP_Timer0_REG      (*(u32 volatile*)(GPT_Timer0_BASE+GPT_MPP_OFFSET))
#define GPT_MTAPR_Timer0_REG    (*(u32 volatile*)(GPT_Timer0_BASE+GPT_MTAPR_OFFSET))
#define GPT_MTBPR_Timer0_REG    (*(u32 volatile*)(GPT_Timer0_BASE+GPT_MTBPR_OFFSET))
#define GPT_MTBILR_Timer0_REG   (*(u32 volatile*)(GPT_Timer0_BASE+GPT_MTAILR_OFFSET))
#define GPT_MTAILR_Timer0_REG   (*(u32 volatile*)(GPT_Timer0_BASE+GPT_MTBILR_OFFSET))
	

#define GPT_MIMR_Timer1_REG     (*(u32 volatile*)(GPT_Timer1_BASE+GPT_MIMR_OFFSET))
#define GPT_MCFG_Timer1_REG     (*(u32 volatile*)(GPT_Timer1_BASE+GPT_MCFG_OFFSET))
#define GPT_MTAV_Timer1_REG     (*(u32 volatile*)(GPT_Timer1_BASE+GPT_MTAV_OFFSET))
#define GPT_MCTL_Timer1_REG     (*(u32 volatile*)(GPT_Timer1_BASE+GPT_MCTL_OFFSET))
#define GPT_MTAMR_Timer1_REG    (*(u32 volatile*)(GPT_Timer1_BASE+GPT_MTAMR_OFFSET))
#define GPT_MTBMR_Timer1_REG    (*(u32 volatile*)(GPT_Timer1_BASE+GPT_MTBMR_OFFSET))
#define GPT_MTAPS_Timer1_REG    (*(u32 volatile*)(GPT_Timer1_BASE+GPT_MTAPS_OFFSET))
#define GPT_MTBPS_Timer1_REG    (*(u32 volatile*)(GPT_Timer1_BASE+GPT_MTBPS_OFFSET))
#define GPT_MTAPV_Timer1_REG    (*(u32 volatile*)(GPT_Timer1_BASE+GPT_MTAPV_OFFSET))
#define GPT_MTBPV_Timer1_REG    (*(u32 volatile*)(GPT_Timer1_BASE+GPT_MTBPV_OFFSET))
#define GPT_MPP_Timer1_REG      (*(u32 volatile*)(GPT_Timer1_BASE+GPT_MPP_OFFSET))
#define GPT_MTAPR_Timer1_REG    (*(u32 volatile*)(GPT_Timer1_BASE+GPT_MTAPR_OFFSET))
#define GPT_MTBPR_Timer1_REG    (*(u32 volatile*)(GPT_Timer1_BASE+GPT_MTBPR_OFFSET))
#define GPT_MTBILR_Timer1_REG   (*(u32 volatile*)(GPT_Timer1_BASE+GPT_MTAILR_OFFSET))
#define GPT_MTAILR_Timer1_REG   (*(u32 volatile*)(GPT_Timer1_BASE+GPT_MTBILR_OFFSET))
#define GPT_MICR_Timer1_REG    	(*(u32 volatile*)(GPT_Timer1_BASE+GPT_MTBILR_OFFSET))


#define GPT_MIMR_Timer2_REG     (*(u32 volatile*)(GPT_Timer2_BASE+GPT_MIMR_OFFSET))
#define GPT_MCFG_Timer2_REG     (*(u32 volatile*)(GPT_Timer2_BASE+GPT_MCFG_OFFSET))
#define GPT_MTAV_Timer2_REG     (*(u32 volatile*)(GPT_Timer2_BASE+GPT_MTAV_OFFSET))
#define GPT_MCTL_Timer2_REG     (*(u32 volatile*)(GPT_Timer2_BASE+GPT_MCTL_OFFSET))
#define GPT_MTAMR_Timer2_REG    (*(u32 volatile*)(GPT_Timer2_BASE+GPT_MTAMR_OFFSET))
#define GPT_MTBMR_Timer2_REG    (*(u32 volatile*)(GPT_Timer2_BASE+GPT_MTBMR_OFFSET))
#define GPT_MTAPS_Timer2_REG    (*(u32 volatile*)(GPT_Timer2_BASE+GPT_MTAPS_OFFSET))
#define GPT_MTBPS_Timer2_REG    (*(u32 volatile*)(GPT_Timer2_BASE+GPT_MTBPS_OFFSET))
#define GPT_MTAPV_Timer2_REG    (*(u32 volatile*)(GPT_Timer2_BASE+GPT_MTAPV_OFFSET))
#define GPT_MTBPV_Timer2_REG    (*(u32 volatile*)(GPT_Timer2_BASE+GPT_MTBPV_OFFSET))
#define GPT_MPP_Timer2_REG      (*(u32 volatile*)(GPT_Timer2_BASE+GPT_MPP_OFFSET))
#define GPT_MTAPR_Timer2_REG    (*(u32 volatile*)(GPT_Timer2_BASE+GPT_MTAPR_OFFSET))
#define GPT_MTBPR_Timer2_REG    (*(u32 volatile*)(GPT_Timer2_BASE+GPT_MTBPR_OFFSET))
#define GPT_MTBILR_Timer2_REG   (*(u32 volatile*)(GPT_Timer2_BASE+GPT_MTAILR_OFFSET))
#define GPT_MTAILR_Timer2_REG   (*(u32 volatile*)(GPT_Timer2_BASE+GPT_MTBILR_OFFSET))
	

#define GPT_MIMR_Timer3_REG     (*(u32 volatile*)(GPT_Timer3_BASE+GPT_MIMR_OFFSET))
#define GPT_MCFG_Timer3_REG     (*(u32 volatile*)(GPT_Timer3_BASE+GPT_MCFG_OFFSET))
#define GPT_MTAV_Timer3_REG     (*(u32 volatile*)(GPT_Timer3_BASE+GPT_MTAV_OFFSET))
#define GPT_MCTL_Timer3_REG     (*(u32 volatile*)(GPT_Timer3_BASE+GPT_MCTL_OFFSET))
#define GPT_MTAMR_Timer3_REG    (*(u32 volatile*)(GPT_Timer3_BASE+GPT_MTAMR_OFFSET))
#define GPT_MTBMR_Timer3_REG    (*(u32 volatile*)(GPT_Timer3_BASE+GPT_MTBMR_OFFSET))
#define GPT_MTAPS_Timer3_REG    (*(u32 volatile*)(GPT_Timer3_BASE+GPT_MTAPS_OFFSET))
#define GPT_MTBPS_Timer3_REG    (*(u32 volatile*)(GPT_Timer3_BASE+GPT_MTBPS_OFFSET))
#define GPT_MTAPV_Timer3_REG    (*(u32 volatile*)(GPT_Timer3_BASE+GPT_MTAPV_OFFSET))
#define GPT_MTBPV_Timer3_REG    (*(u32 volatile*)(GPT_Timer3_BASE+GPT_MTBPV_OFFSET))
#define GPT_MPP_Timer3_REG      (*(u32 volatile*)(GPT_Timer3_BASE+GPT_MPP_OFFSET))
#define GPT_MTAPR_Timer3_REG    (*(u32 volatile*)(GPT_Timer3_BASE+GPT_MTAPR_OFFSET))
#define GPT_MTBPR_Timer3_REG    (*(u32 volatile*)(GPT_Timer3_BASE+GPT_MTBPR_OFFSET))
#define GPT_MTBILR_Timer3_REG   (*(u32 volatile*)(GPT_Timer3_BASE+GPT_MTAILR_OFFSET))
#define GPT_MTAILR_Timer3_REG   (*(u32 volatile*)(GPT_Timer3_BASE+GPT_MTBILR_OFFSET))
	

#define GPT_MIMR_Timer4_REG     (*(u32 volatile*)(GPT_Timer4_BASE+GPT_MIMR_OFFSET))
#define GPT_MCFG_Timer4_REG     (*(u32 volatile*)(GPT_Timer4_BASE+GPT_MCFG_OFFSET))
#define GPT_MTAV_Timer4_REG     (*(u32 volatile*)(GPT_Timer4_BASE+GPT_MTAV_OFFSET))
#define GPT_MCTL_Timer4_REG     (*(u32 volatile*)(GPT_Timer4_BASE+GPT_MCTL_OFFSET))
#define GPT_MTAMR_Timer4_REG    (*(u32 volatile*)(GPT_Timer4_BASE+GPT_MTAMR_OFFSET))
#define GPT_MTBMR_Timer4_REG    (*(u32 volatile*)(GPT_Timer4_BASE+GPT_MTBMR_OFFSET))
#define GPT_MTAPS_Timer4_REG    (*(u32 volatile*)(GPT_Timer4_BASE+GPT_MTAPS_OFFSET))
#define GPT_MTBPS_Timer4_REG    (*(u32 volatile*)(GPT_Timer4_BASE+GPT_MTBPS_OFFSET))
#define GPT_MTAPV_Timer4_REG    (*(u32 volatile*)(GPT_Timer4_BASE+GPT_MTAPV_OFFSET))
#define GPT_MTBPV_Timer4_REG    (*(u32 volatile*)(GPT_Timer4_BASE+GPT_MTBPV_OFFSET))
#define GPT_MPP_Timer4_REG      (*(u32 volatile*)(GPT_Timer4_BASE+GPT_MPP_OFFSET))
#define GPT_MTAPR_Timer4_REG    (*(u32 volatile*)(GPT_Timer4_BASE+GPT_MTAPR_OFFSET))
#define GPT_MTBPR_Timer4_REG    (*(u32 volatile*)(GPT_Timer4_BASE+GPT_MTBPR_OFFSET))
#define GPT_MTBILR_Timer4_REG   (*(u32 volatile*)(GPT_Timer4_BASE+GPT_MTAILR_OFFSET))
#define GPT_MTAILR_Timer4_REG   (*(u32 volatile*)(GPT_Timer4_BASE+GPT_MTBILR_OFFSET))
	

#define GPT_MIMR_Timer5_REG     (*(u32 volatile*)(GPT_Timer5_BASE+GPT_MIMR_OFFSET))
#define GPT_MCFG_Timer5_REG     (*(u32 volatile*)(GPT_Timer5_BASE+GPT_MCFG_OFFSET))
#define GPT_MTAV_Timer5_REG     (*(u32 volatile*)(GPT_Timer5_BASE+GPT_MTAV_OFFSET))
#define GPT_MCTL_Timer5_REG     (*(u32 volatile*)(GPT_Timer5_BASE+GPT_MCTL_OFFSET))
#define GPT_MTAMR_Timer5_REG    (*(u32 volatile*)(GPT_Timer5_BASE+GPT_MTAMR_OFFSET))
#define GPT_MTBMR_Timer5_REG    (*(u32 volatile*)(GPT_Timer5_BASE+GPT_MTBMR_OFFSET))
#define GPT_MTAPS_Timer5_REG    (*(u32 volatile*)(GPT_Timer5_BASE+GPT_MTAPS_OFFSET))
#define GPT_MTBPS_Timer5_REG    (*(u32 volatile*)(GPT_Timer5_BASE+GPT_MTBPS_OFFSET))
#define GPT_MTAPV_Timer5_REG    (*(u32 volatile*)(GPT_Timer5_BASE+GPT_MTAPV_OFFSET))
#define GPT_MTBPV_Timer5_REG    (*(u32 volatile*)(GPT_Timer5_BASE+GPT_MTBPV_OFFSET))
#define GPT_MPP_Timer5_REG      (*(u32 volatile*)(GPT_Timer5_BASE+GPT_MPP_OFFSET))
#define GPT_MTAPR_Timer5_REG    (*(u32 volatile*)(GPT_Timer5_BASE+GPT_MTAPR_OFFSET))
#define GPT_MTBPR_Timer5_REG    (*(u32 volatile*)(GPT_Timer5_BASE+GPT_MTBPR_OFFSET))
#define GPT_MTBILR_Timer5_REG   (*(u32 volatile*)(GPT_Timer5_BASE+GPT_MTAILR_OFFSET))
#define GPT_MTAILR_Timer5_REG   (*(u32 volatile*)(GPT_Timer5_BASE+GPT_MTBILR_OFFSET))


#define GPT_MIMR_WIDE_Timer0_REG     (*(u32 volatile*)(GPT_WIDE_Timer0_BASE+GPT_MIMR_OFFSET))
#define GPT_MCFG_WIDE_Timer0_REG     (*(u32 volatile*)(GPT_WIDE_Timer0_BASE+GPT_MCFG_OFFSET))
#define GPT_MTAV_WIDE_Timer0_REG     (*(u32 volatile*)(GPT_WIDE_Timer0_BASE+GPT_MTAV_OFFSET))
#define GPT_MCTL_WIDE_Timer0_REG     (*(u32 volatile*)(GPT_WIDE_Timer0_BASE+GPT_MCTL_OFFSET))
#define GPT_MTAMR_WIDE_Timer0_REG    (*(u32 volatile*)(GPT_WIDE_Timer0_BASE+GPT_MTAMR_OFFSET))
#define GPT_MTBMR_WIDE_Timer0_REG    (*(u32 volatile*)(GPT_WIDE_Timer0_BASE+GPT_MTBMR_OFFSET))
#define GPT_MTAPS_WIDE_Timer0_REG    (*(u32 volatile*)(GPT_WIDE_Timer0_BASE+GPT_MTAPS_OFFSET))
#define GPT_MTBPS_WIDE_Timer0_REG    (*(u32 volatile*)(GPT_WIDE_Timer0_BASE+GPT_MTBPS_OFFSET))
#define GPT_MTAPV_WIDE_Timer0_REG    (*(u32 volatile*)(GPT_WIDE_Timer0_BASE+GPT_MTAPV_OFFSET))
#define GPT_MTBPV_WIDE_Timer0_REG    (*(u32 volatile*)(GPT_WIDE_Timer0_BASE+GPT_MTBPV_OFFSET))
#define GPT_MPP_WIDE_Timer0_REG    	 (*(u32 volatile*)(GPT_WIDE_Timer0_BASE+GPT_MPP_OFFSET))
#define GPT_MTAPR_WIDE_Timer0_REG    (*(u32 volatile*)(GPT_WIDE_Timer0_BASE+GPT_MTAPR_OFFSET))
#define GPT_MTBPR_WIDE_Timer0_REG    (*(u32 volatile*)(GPT_WIDE_Timer0_BASE+GPT_MTBPR_OFFSET))
#define GPT_MTBILR_WIDE_Timer0_REG   (*(u32 volatile*)(GPT_WIDE_Timer0_BASE+GPT_MTAILR_OFFSET))
#define GPT_MTAILR_WIDE_Timer0_REG   (*(u32 volatile*)(GPT_WIDE_Timer0_BASE+GPT_MTBILR_OFFSET))


#define GPT_MIMR_WIDE_Timer1_REG     (*(u32 volatile*)(GPT_WIDE_Timer1_BASE+GPT_MIMR_OFFSET))
#define GPT_MCFG_WIDE_Timer1_REG     (*(u32 volatile*)(GPT_WIDE_Timer1_BASE+GPT_MCFG_OFFSET))
#define GPT_MTAV_WIDE_Timer1_REG     (*(u32 volatile*)(GPT_WIDE_Timer1_BASE+GPT_MTAV_OFFSET))
#define GPT_MCTL_WIDE_Timer1_REG     (*(u32 volatile*)(GPT_WIDE_Timer1_BASE+GPT_MCTL_OFFSET))
#define GPT_MTAMR_WIDE_Timer1_REG    (*(u32 volatile*)(GPT_WIDE_Timer1_BASE+GPT_MTAMR_OFFSET))
#define GPT_MTBMR_WIDE_Timer1_REG    (*(u32 volatile*)(GPT_WIDE_Timer1_BASE+GPT_MTBMR_OFFSET))
#define GPT_MTAPS_WIDE_Timer1_REG    (*(u32 volatile*)(GPT_WIDE_Timer1_BASE+GPT_MTAPS_OFFSET))
#define GPT_MTBPS_WIDE_Timer1_REG    (*(u32 volatile*)(GPT_WIDE_Timer1_BASE+GPT_MTBPS_OFFSET))
#define GPT_MTAPV_WIDE_Timer1_REG    (*(u32 volatile*)(GPT_WIDE_Timer1_BASE+GPT_MTAPV_OFFSET))
#define GPT_MTBPV_WIDE_Timer1_REG    (*(u32 volatile*)(GPT_WIDE_Timer1_BASE+GPT_MTBPV_OFFSET))
#define GPT_MPP_WIDE_Timer1_REG    	 (*(u32 volatile*)(GPT_WIDE_Timer1_BASE+GPT_MPP_OFFSET))
#define GPT_MTAPR_WIDE_Timer1_REG    (*(u32 volatile*)(GPT_WIDE_Timer1_BASE+GPT_MTAPR_OFFSET))
#define GPT_MTBPR_WIDE_Timer1_REG    (*(u32 volatile*)(GPT_WIDE_Timer1_BASE+GPT_MTBPR_OFFSET))
#define GPT_MTBILR_WIDE_Timer1_REG   (*(u32 volatile*)(GPT_WIDE_Timer1_BASE+GPT_MTAILR_OFFSET))
#define GPT_MTAILR_WIDE_Timer1_REG   (*(u32 volatile*)(GPT_WIDE_Timer1_BASE+GPT_MTBILR_OFFSET))
	

#define GPT_MIMR_WIDE_Timer2_REG     (*(u32 volatile*)(GPT_WIDE_Timer2_BASE+GPT_MIMR_OFFSET))
#define GPT_MCFG_WIDE_Timer2_REG     (*(u32 volatile*)(GPT_WIDE_Timer2_BASE+GPT_MCFG_OFFSET))
#define GPT_MTAV_WIDE_Timer2_REG     (*(u32 volatile*)(GPT_WIDE_Timer2_BASE+GPT_MTAV_OFFSET))
#define GPT_MCTL_WIDE_Timer2_REG     (*(u32 volatile*)(GPT_WIDE_Timer2_BASE+GPT_MCTL_OFFSET))
#define GPT_MTAMR_WIDE_Timer2_REG    (*(u32 volatile*)(GPT_WIDE_Timer2_BASE+GPT_MTAMR_OFFSET))
#define GPT_MTBMR_WIDE_Timer2_REG    (*(u32 volatile*)(GPT_WIDE_Timer2_BASE+GPT_MTBMR_OFFSET))
#define GPT_MTAPS_WIDE_Timer2_REG    (*(u32 volatile*)(GPT_WIDE_Timer2_BASE+GPT_MTAPS_OFFSET))
#define GPT_MTBPS_WIDE_Timer2_REG    (*(u32 volatile*)(GPT_WIDE_Timer2_BASE+GPT_MTBPS_OFFSET))
#define GPT_MTAPV_WIDE_Timer2_REG    (*(u32 volatile*)(GPT_WIDE_Timer2_BASE+GPT_MTAPV_OFFSET))
#define GPT_MTBPV_WIDE_Timer2_REG    (*(u32 volatile*)(GPT_WIDE_Timer2_BASE+GPT_MTBPV_OFFSET))
#define GPT_MPP_WIDE_Timer2_REG    	 (*(u32 volatile*)(GPT_WIDE_Timer2_BASE+GPT_MPP_OFFSET))
#define GPT_MTAPR_WIDE_Timer2_REG    (*(u32 volatile*)(GPT_WIDE_Timer2_BASE+GPT_MTAPR_OFFSET))
#define GPT_MTBPR_WIDE_Timer2_REG    (*(u32 volatile*)(GPT_WIDE_Timer2_BASE+GPT_MTBPR_OFFSET))
#define GPT_MTBILR_WIDE_Timer2_REG   (*(u32 volatile*)(GPT_WIDE_Timer2_BASE+GPT_MTAILR_OFFSET))
#define GPT_MTAILR_WIDE_Timer2_REG   (*(u32 volatile*)(GPT_WIDE_Timer2_BASE+GPT_MTBILR_OFFSET))
	

#define GPT_MIMR_WIDE_Timer3_REG     (*(u32 volatile*)(GPT_WIDE_Timer3_BASE+GPT_MIMR_OFFSET))
#define GPT_MCFG_WIDE_Timer3_REG     (*(u32 volatile*)(GPT_WIDE_Timer3_BASE+GPT_MCFG_OFFSET))
#define GPT_MTAV_WIDE_Timer3_REG     (*(u32 volatile*)(GPT_WIDE_Timer3_BASE+GPT_MTAV_OFFSET))
#define GPT_MCTL_WIDE_Timer3_REG     (*(u32 volatile*)(GPT_WIDE_Timer3_BASE+GPT_MCTL_OFFSET))
#define GPT_MTAMR_WIDE_Timer3_REG    (*(u32 volatile*)(GPT_WIDE_Timer3_BASE+GPT_MTAMR_OFFSET))
#define GPT_MTBMR_WIDE_Timer3_REG    (*(u32 volatile*)(GPT_WIDE_Timer3_BASE+GPT_MTBMR_OFFSET))
#define GPT_MTAPS_WIDE_Timer3_REG    (*(u32 volatile*)(GPT_WIDE_Timer3_BASE+GPT_MTAPS_OFFSET))
#define GPT_MTBPS_WIDE_Timer3_REG    (*(u32 volatile*)(GPT_WIDE_Timer3_BASE+GPT_MTBPS_OFFSET))
#define GPT_MTAPV_WIDE_Timer3_REG    (*(u32 volatile*)(GPT_WIDE_Timer3_BASE+GPT_MTAPV_OFFSET))
#define GPT_MTBPV_WIDE_Timer3_REG    (*(u32 volatile*)(GPT_WIDE_Timer3_BASE+GPT_MTBPV_OFFSET))
#define GPT_MPP_WIDE_Timer3_REG    	 (*(u32 volatile*)(GPT_WIDE_Timer3_BASE+GPT_MPP_OFFSET))
#define GPT_MTAPR_WIDE_Timer3_REG    (*(u32 volatile*)(GPT_WIDE_Timer3_BASE+GPT_MTAPR_OFFSET))
#define GPT_MTBPR_WIDE_Timer3_REG    (*(u32 volatile*)(GPT_WIDE_Timer3_BASE+GPT_MTBPR_OFFSET))
#define GPT_MTBILR_WIDE_Timer3_REG   (*(u32 volatile*)(GPT_WIDE_Timer3_BASE+GPT_MTAILR_OFFSET))
#define GPT_MTAILR_WIDE_Timer3_REG   (*(u32 volatile*)(GPT_WIDE_Timer3_BASE+GPT_MTBILR_OFFSET))
	

#define GPT_MIMR_WIDE_Timer4_REG     (*(u32 volatile*)(GPT_WIDE_Timer4_BASE+GPT_MIMR_OFFSET))
#define GPT_MCFG_WIDE_Timer4_REG     (*(u32 volatile*)(GPT_WIDE_Timer4_BASE+GPT_MCFG_OFFSET))
#define GPT_MTAV_WIDE_Timer4_REG     (*(u32 volatile*)(GPT_WIDE_Timer4_BASE+GPT_MTAV_OFFSET))
#define GPT_MCTL_WIDE_Timer4_REG     (*(u32 volatile*)(GPT_WIDE_Timer4_BASE+GPT_MCTL_OFFSET))
#define GPT_MTAMR_WIDE_Timer4_REG    (*(u32 volatile*)(GPT_WIDE_Timer4_BASE+GPT_MTAMR_OFFSET))
#define GPT_MTBMR_WIDE_Timer4_REG    (*(u32 volatile*)(GPT_WIDE_Timer4_BASE+GPT_MTBMR_OFFSET))
#define GPT_MTAPS_WIDE_Timer4_REG    (*(u32 volatile*)(GPT_WIDE_Timer4_BASE+GPT_MTAPS_OFFSET))
#define GPT_MTBPS_WIDE_Timer4_REG    (*(u32 volatile*)(GPT_WIDE_Timer4_BASE+GPT_MTBPS_OFFSET))
#define GPT_MTAPV_WIDE_Timer4_REG    (*(u32 volatile*)(GPT_WIDE_Timer4_BASE+GPT_MTAPV_OFFSET))
#define GPT_MTBPV_WIDE_Timer4_REG    (*(u32 volatile*)(GPT_WIDE_Timer4_BASE+GPT_MTBPV_OFFSET))
#define GPT_MPP_WIDE_Timer4_REG    	 (*(u32 volatile*)(GPT_WIDE_Timer4_BASE+GPT_MPP_OFFSET))
#define GPT_MTAPR_WIDE_Timer4_REG    (*(u32 volatile*)(GPT_WIDE_Timer4_BASE+GPT_MTAPR_OFFSET))
#define GPT_MTBPR_WIDE_Timer4_REG    (*(u32 volatile*)(GPT_WIDE_Timer4_BASE+GPT_MTBPR_OFFSET))
#define GPT_MTBILR_WIDE_Timer4_REG   (*(u32 volatile*)(GPT_WIDE_Timer4_BASE+GPT_MTAILR_OFFSET))
#define GPT_MTAILR_WIDE_Timer4_REG   (*(u32 volatile*)(GPT_WIDE_Timer4_BASE+GPT_MTBILR_OFFSET))
	

#define GPT_MIMR_WIDE_Timer5_REG     (*(u32 volatile*)(GPT_WIDE_Timer5_BASE+GPT_MIMR_OFFSET))
#define GPT_MCFG_WIDE_Timer5_REG     (*(u32 volatile*)(GPT_WIDE_Timer5_BASE+GPT_MCFG_OFFSET))
#define GPT_MTAV_WIDE_Timer5_REG     (*(u32 volatile*)(GPT_WIDE_Timer5_BASE+GPT_MTAV_OFFSET))
#define GPT_MCTL_WIDE_Timer5_REG     (*(u32 volatile*)(GPT_WIDE_Timer5_BASE+GPT_MCTL_OFFSET))
#define GPT_MTAMR_WIDE_Timer5_REG    (*(u32 volatile*)(GPT_WIDE_Timer5_BASE+GPT_MTAMR_OFFSET))
#define GPT_MTBMR_WIDE_Timer5_REG    (*(u32 volatile*)(GPT_WIDE_Timer5_BASE+GPT_MTBMR_OFFSET))
#define GPT_MTAPS_WIDE_Timer5_REG    (*(u32 volatile*)(GPT_WIDE_Timer5_BASE+GPT_MTAPS_OFFSET))
#define GPT_MTBPS_WIDE_Timer5_REG    (*(u32 volatile*)(GPT_WIDE_Timer5_BASE+GPT_MTBPS_OFFSET))
#define GPT_MTAPV_WIDE_Timer5_REG    (*(u32 volatile*)(GPT_WIDE_Timer5_BASE+GPT_MTAPV_OFFSET))
#define GPT_MTBPV_WIDE_Timer5_REG    (*(u32 volatile*)(GPT_WIDE_Timer5_BASE+GPT_MTBPV_OFFSET))
#define GPT_MPP_WIDE_Timer5_REG    	 (*(u32 volatile*)(GPT_WIDE_Timer5_BASE+GPT_MPP_OFFSET))
#define GPT_MTAPR_WIDE_Timer5_REG    (*(u32 volatile*)(GPT_WIDE_Timer5_BASE+GPT_MTAPR_OFFSET))
#define GPT_MTBPR_WIDE_Timer5_REG    (*(u32 volatile*)(GPT_WIDE_Timer5_BASE+GPT_MTBPR_OFFSET))
#define GPT_MTBILR_WIDE_Timer5_REG   (*(u32 volatile*)(GPT_WIDE_Timer5_BASE+GPT_MTAILR_OFFSET))
#define GPT_MTAILR_WIDE_Timer5_REG   (*(u32 volatile*)(GPT_WIDE_Timer5_BASE+GPT_MTBILR_OFFSET))


#endif /* Timers_Reg_H_ */